primitive:
        name: cubicgrad
        size: 150

optimizer:
        name: adamw
        lr: 0.005
        weight_decay: 0.0001
scheduler:
        name: step
        step_size: 50
        gamma: 0.75

losses:
      #       - L2:
      #                 weight: 1.0
      #       - SSIM:
      #                 weight: 0.25
      - L1:
                weight: 1.0

callbacks:
      - LoopControl:
                epochs: 10000
      - PrimitiveCheckpoint:
                interval: 50
      - LossLogger: {}
      - PreviewWindow: {}

refinement:
      #       - AlphaCull:
      #                 threshold: 0.1
      #                 interval: 25
      - GradSplit:
                threshold: 0.05
                interval: 50
      - IsoSplit:
                threshold: 2
                interval: 50

trainer:
        name: cubic_test
        patch_size: 16

target:
        path: examples/target.png
        mode: RGBA
        normalize: false
